SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_CLASS;
SELECT * FROM tb_student;
--1.
SELECT DEPARTMENT_NAME "학과 명", CATEGORY"계열"
FROM TB_DEPARTMENT;
--2
SELECT CONCAT(DEPARTMENT_NAME||'의 정원은 ', CAPACITY ||' 명입니다')
FROM  TB_DEPARTMENT;
--3
SELECT STUDENT_NAME, SUBSTR( STUDENT_SSN,8, 1), ABSENCE_YN  
FROM  tb_student
JOIN TB_DEPARTMENT USING (department_no)
WHERE (ABSENCE_YN ='Y') AND (SUBSTR( STUDENT_SSN,8, 1)=2) 
AND STUDENT_NAME = '한수현';