-- 모든 사람의 정보 조회
SELECT*FROM CUSTOMER; 

-- 광역시에 거주 중인 사람들의 정보 조회
SELECT ADDRESS  
FROM CUSTOMER
WHERE ADDRESS LIKE  '%광역시%'; 
-- 이름이 2자인 사람들의 정보 조회
SELECT*FROM CUSTOMER
WHERE LENGTH(NAME) = 2; 
--WHERE MAME LIKE '__';

SELECT NAME, BIRTHDATE, 
EXTRACT (YEAR FROM SYSDATE)- EXTRACT (YEAR FROM birthdate)+1 "나이" 
FROM CUSTOMER; 

SELECT*FROM CUSTOMER
WHERE EXTRACT (YEAR FROM SYSDATE)- EXTRACT (YEAR FROM birthdate)+1 BETWEEN 30 AND 39;       